# Generated by Django 5.2.12 on 2026-03-17 09:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrashRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('server_seed', models.CharField(max_length=64)),
                ('server_seed_hash', models.CharField(max_length=64)),
                ('client_seed', models.CharField(default='', max_length=64)),
                ('nonce', models.PositiveIntegerField(default=0)),
                ('crash_point', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('BETTING', 'Betting'), ('RUNNING', 'Running'), ('CRASHED', 'Crashed')], default='BETTING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('crashed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('DICE', 'Dice'), ('MINES', 'Mines'), ('PLINKO', 'Plinko'), ('CRASH', 'Crash')], max_length=20)),
                ('currency_code', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost'), ('CASHED_OUT', 'Cashed Out')], default='PENDING', max_length=20)),
                ('payout', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('outcome', models.JSONField(blank=True, null=True)),
                ('bet_transaction_id', models.BigIntegerField(blank=True, null=True)),
                ('win_transaction_id', models.BigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'game_type'], name='games_bet_user_id_e36b2c_idx'), models.Index(fields=['user', 'created_at'], name='games_bet_user_id_93e3bc_idx')],
            },
        ),
    ]
