# Generated by Django 5.2.12 on 2026-03-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='game_type',
            field=models.CharField(choices=[('DICE', 'Dice'), ('MINES', 'Mines'), ('PLINKO', 'Plinko'), ('CRASH', 'Crash'), ('SPORTS', 'Sports')], max_length=20),
        ),
    ]
