# Generated by Django 5.2.12 on 2026-03-17 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=10)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('gateway', models.CharField(max_length=20)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_deposits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
