# Generated by Django 5.2.12 on 2026-03-17 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_add_pending_deposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingWithdrawal',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Withdrawal',
                'verbose_name_plural': 'Pending Withdrawals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wallets.transaction',),
        ),
    ]
