# Generated by Django 5.2.12 on 2026-03-17 14:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_pendingwithdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='vault_balance',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20),
        ),
    ]
